sudo: false

language: php

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install: phpenv config-rm xdebug.ini || true

install: composer install

before_script:
  - php-cs-fixer fix --diff --dry-run
  - psalm --show-info=false

script: vendor/bin/phpunit --coverage-text
