version: '3.4'

services:
  app:
    container_name: icbot-app
    build:
      context: .
      target: development
    environment:
      VIRTUAL_HOST: icbot.local
    volumes:
      - ./:/var/www/html
    restart: unless-stopped

networks:
  default:
    external:
      name: development
