version: '3.4'

services:
  app:
    container_name: inner-circle-bot-app
    build: .
    environment:
      TZ: ${APP_TZ:-America/Phoenix}
      VIRTUAL_HOST: ${APP_URL:-icbot.local}
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP:-0.0.0.0}
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.conf:/etc/apache2/sites-available/000-default.conf

networks:
  default:
    external:
      name: development
