version: '3.4'

services:
  app:
    container_name: icbot-app
    build:
      context: .
      target: development
    environment:
      TZ: America/Phoenix
      VIRTUAL_HOST: icbot.local
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP}
    volumes:
      - ./:/var/www/html

networks:
  default:
    external:
      name: development
